export enum Role {
  PROJECT_MANAGER = "PROJECT_MANAGER",
  DEPUTY_PROJECT_MANAGER = "DEPUTY_PROJECT_MANAGER",
  ASSOCIATE = "ASSOCIATE",
  SOLUTION_ARCHITECT = "SOLUTION_ARCHITECT",
  SOFTWARE_ARCHITECT = "SOFTWARE_ARCHITECT",
  SOFTWARE_ENGINEER = "SOFTWARE_ENGINEER"
}
